spring:
  application:
    name: namatdang

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${DB_URL:jdbc:mysql://localhost:${MYSQL_PORT:3306}/${MYSQL_DATABASE:namatdang}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}"
    username: "${DB_USERNAME:${MYSQL_USER:root}}"
    password: "${DB_PASSWORD:${MYSQL_PASSWORD:}}"

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

security:
  jwt:
    private-key-base64: "${JWT_PRIVATE_KEY_BASE64:}"
    public-key-base64: "${JWT_PUBLIC_KEY_BASE64:}"
    access-token-expiration-seconds: "${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}"
